### ISSUE TITLE
Documentation or explanation for Abstract vs. Reified types

### ISSUE THREAD

**Issue by H2CO3** [Schwenger/RustTyC#3]
Hi, and thanks for making this awesome library!

I'm having trouble finding what your interpretation of "abstract", "concrete", and "reified" types is. Terminology around these concepts is not universal, to say the least. Could you please add some documentation, or briefly clarify in response:
 - What specifically the difference is between abstract vs concrete vs reified types, *in the context of this library;*
 - What you mean by reifying abstract types; and
 - When or why I would need to transform the abstract type table produced by type checking into a reified one.

Thanks!

**Comment by Schwenger** [comment]
Hey,

thanks, it was my pleasure to write it!

I perfectly understand the confusion.  Let me try to elaborate here and if it helps, I'll incorporate it into the documentation.

- The _abstract type_ is the type the user provides.  It is abstract in the sense that it can be something like "top" meaning that the type has not been inferred, yet, or "numeric" as a super category for anything related to numbers.  The abstract type needs to implement the `rusttyc::types::Abstract' trait.
- The _concrete type_ is a type that has been fully inferred.  From the user perspective, the concrete type contains all types that can occur in their program.  This can be "String" or "int" in Java.
- The _reified type_ is per se not a new category of types.  Given an abstract type, its reification is a concrete type.  For example, if your type system states that any "numeric" type is by default an "int", then the reification of "numeric" is "int".

You never _need_ to generate a reified type table out of an abstract type table.  It is just a convenience function mapping each abstract type to their respective reified (i.e. concrete) type.  The workflow might be: create type checker, impose constraints, generate the abstract type table.  If it failed, there was a type error such as an overconstrained type.  If it succeeded, transform the abstract type table into a reified type table.  If this fails, a type was underconstrained (e.g. type "Any" has no default type).  If it succeeds, you can continue to work with the concrete types and do not have to bother with types irrelevant after type inference.

Does this clear things up?

**Comment by H2CO3** [comment]
Oh, yes, perfectly – thanks for the clear explanation! So basically reification makes it possible for me to work, after inference is completed, with types not containing things like `Unconstrained`, without the need to always assert them away or otherwise handle them once they are proven not to exist anymore. That does make sense.
