### ISSUE TITLE
Update blog URL

### ISSUE THREAD

**Issue by pandaman64** [Schwenger/RustTyC#4]
I'm interested in the typing rules of this system but the blog URL on the README.md (https://mschwenger.de/rusttyc) seems not working.
Can you update the URL?

**Comment by Schwenger** [comment]
Hey pandaman64,

I'm quite literally in the process of re-writing the post after the last major release, so please hang on for a couple more days.  I'll let you know when it's done.

**Comment by Schwenger** [comment]
Hey, 
good news! The revised blog post is up: https://mschwenger.de/projects/rusttyc.html
Hope you like it, let me know if you have any feedback or questions.
